### ISSUE TITLE
Validate EMPLID is 8 digits long

### ISSUE THREAD

**Issue by mgarod** [IgorGee/Attendance-Tracker#26]
is there a smarter way than 9999999 < x < 100000000 (more than 7 digits and less than 9 digits)?

**Comment by IgorGee** [comment]
This method is more flexible with your input. You can check what's in the TextField every time the content of it changes. So you can reject non-numeric characters and reject input past a certain limit.

[StackOverflow](http://stackoverflow.com/questions/22714268/how-to-limit-the-amount-of-characters-a-javafx-textfield)

**Comment by mgarod** [comment]
I totally wasn't expecting you to answer. I was just using this space as a notepad.
Thanks I'll look into it.

**Comment by IgorGee** [comment]
I know, but this wasn't a trivial issue so I thought I'd help out lol

**Comment by mgarod** [comment]
Partial solution:
If user submits an EMPLID that cannot be parsed to int, throw a pop up and erase what the user wrote.
[ea07086b003a462f1b95783074c360e17f72bdcb]
