### ISSUE TITLE
Remove whitespace from enum Courses

### ISSUE THREAD

**Issue by mgarod** [IgorGee/Attendance-Tracker#6]
Having whitespace in "CSCI XXX" is unnecessary and can cause difficulty when traversing the database later since I'm using this as a key.

**Comment by IgorGee** [comment]
I don't see how it would cause difficulty.
Can you show me an example of how you're traversing through the database?

**Comment by mgarod** [comment]
Tested it. It works out. I still very much so no need to use white space. It's confusing. I still want it removed.

**Comment by IgorGee** [comment]
Fixed with commit cacba01ff3d55396d0c66444f01707ea6866850c
